version: '2'
services:
    backlog:
        environment:
            SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        build:
            context: .
            args:
               DB_PASS: ${DB_PASS}
               DB_USER: ${DB_USER}
               BACKLOG_DB_URL: ${BACKLOG_DB_URL}
               JWT_SECRET: ${JWT_SECRET}
            dockerfile: Dockerfile